### ISSUE TITLE
运行报错 No module named 'ios_device.remote'

### ISSUE THREAD

**Issue by qzlinfox** [15525730080/iOS17_perf#2]
大佬帮忙看看，执行sudo python main.py后报错

Traceback (most recent call last):
  File "/Users/qzl/code/github/iOS17_perf/main.py", line 15, in <module>
    from ios_device.remote.remote_lockdown import RemoteLockdownClient
ModuleNotFoundError: No module named 'ios_device.remote'

**Comment by WINGSIGOD** [comment]
本问题理应安装完py_ios_device关闭即可

**Comment by 15525730080** [comment]
装包已经内置脚本
