### ISSUE TITLE
用 pycharm 直接执行main 文件，显示权限不够，有办法用python直接运行main文件吗？

### ISSUE THREAD

**Issue by liushijiejob** [15525730080/iOS17_perf#3]
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    assert os.geteuid() == 0, "必须使用sudo权限启动"
AssertionError: 必须使用sudo权限启动

**Comment by liushijiejob** [comment]
mac 上执行

**Comment by 15525730080** [comment]
> mac 上执行

sudo python main.py  这里面启动pymobiledevice3必须要sudo权限。你直接在命令行执行。

**Comment by liushijiejob** [comment]
能用pycharm获取sudo权限。然后pycharm上运行main吗？

**Comment by 15525730080** [comment]
> 能用pycharm获取sudo权限。然后pycharm上运行main吗？

可以用sudo 启动pycharm。找到你的pycharm 启动地址。sudo启动。

**Comment by liushijiejob** [comment]
> > 能用pycharm获取sudo权限。然后pycharm上运行main吗？
> 
> 可以用sudo 启动pycharm。找到你的pycharm 启动地址。sudo启动。

mac 试过了  不行，试过了些办法，pycharm没法用sudo 执行 python 文件

**Comment by 15525730080** [comment]
> > > 能用pycharm获取sudo权限。然后pycharm上运行main吗？
> > 
> > 
> > 可以用sudo 启动pycharm。找到你的pycharm 启动地址。sudo启动。
> 
> mac 试过了 不行，试过了些办法，pycharm没法用sudo 执行 python 文件

<img width="570" alt="image" src="https://github.com/15525730080/iOS17_perf/assets/153100629/1fa7f61e-87fb-46c6-be65-0914848a80ed">

**Comment by 15525730080** [comment]
> Traceback (most recent call last): File "main.py", line 106, in assert os.geteuid() == 0, "必须使用sudo权限启动" AssertionError: 必须使用sudo权限启动

已经自动使用sudo执行
