### ISSUE TITLE
多设备运行性能收集

### ISSUE THREAD

**Issue by WINGSIGOD** [15525730080/iOS17_perf#5]
我这边在想多台设备一起运行main
主要有两个想法
1.根据 https://github.com/doronz88/pymobiledevice3?#usage
在TunnelManager.get_tunnel.start_tunnel(main.py:26)添加--udid函数
但是会产生TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2.将TunnelManager.get_tunnel.start_tunnel(main.py:26)改为使用纯python而不是命令行形式运行

对于RemoteLockdownClient我还研究不太透彻 是需要另外增加udid参数实现吗?
我希望基于此来展开讨论 非常感谢

**Comment by 15525730080** [comment]
> 我这边在想多台设备一起运行main 主要有两个想法 1.根据 https://github.com/doronz88/pymobiledevice3?#usage 在TunnelManager.get_tunnel.start_tunnel(main.py:26)添加--udid函数 但是会产生TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 2.将TunnelManager.get_tunnel.start_tunnel(main.py:26)改为使用纯python而不是命令行形式运行
> 
> 对于RemoteLockdownClient我还研究不太透彻 是需要另外增加udid参数实现吗? 我希望基于此来展开讨论 非常感谢

1.这个脚本里应该是启动了 tunnel 然后 remote 连接instrument 时指定udid。所以可以只启动一个tunnel，创建多个ios的remote
2.RemoteLockdownClient 是链接ios设备内置的instrumentserver 。 链接方式是通过usbmuxd 抽象的tcp。多设备都走的同一个usbmuxd的tcp 所以多设备可能会受制于这个的限制。不过一般没事。
3.这个能力只是针对ios17的。多设备你用ios17以下的覆盖一些不行。ios17以下的用 tidevice sib 等工具都可以直接通信

**Comment by WINGSIGOD** [comment]
那看来是usbmuxd限制了 过于痛苦 非常感谢解答

**Comment by WINGSIGOD** [comment]
已发送请求

**Comment by WINGSIGOD** [comment]
> > 那看来是usbmuxd限制了 过于痛苦 非常感谢解答
> 
> 加我微信 细聊 微信就是我名字

已发送请求
